sonar.projectKey=OnlyMD-321_ci-cd
sonar.organization=onlymd-321
sonar.projectName=todo-api
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,dist/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-report.xml
